AllCops:
  TargetRubyVersion: 2.6.0
  Include:
    - '**/Rakefile'
    - '**/config.ru'
    - '**/Gemfile'
  Exclude:
    - db/**/*
    - vendor/**/*
    - bin/**/*

Rails:
  Enabled: true

Bundler:
  Enabled: true
