language: ruby
cache:
  bundler: true
install:
  - gem install bundler
  - bundle install
before_script:
  - bundle exec rails db:setup RAILS_ENV=test
  - bundle exec rspec
script:
  - bundle exec rubocop
